FROM node:14.0.0-alpine3.10

RUN apk update

RUN apk add nginx

RUN apk add nginx-mod-stream

RUN apk add curl

# RUN mkdir -p /run/nginx

COPY ./video-conference/build /usr/share/nginx/html

COPY ./video-conference/public/.well-known/pki-validation/6B5DDA8B859875ACE2C65D2EF8A6B5ED.txt /usr/share/nginx/html/.well-known/pki-validation/6B5DDA8B859875ACE2C65D2EF8A6B5ED.txt

RUN rm /etc/nginx/conf.d/default.conf

COPY ./video-conference/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 443